dist: trusty
sudo: true

branches:
  only:
  - master

language: go

go:
  - "1.12.x"

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go get sigs.k8s.io/kind
  - apt-get install -y python3 python3-pip

install:
  - make deps
  - pip3 install -r requirements.txt

script:
  - hack/verify-codegen.sh
  - make e2e
  - travis_wait 20 goveralls -service=travis-ci -package ./pkg/... -v
