dist: trusty
sudo: false

branches:
  only:
  - master

language: go

go:
  - "1.12.x"

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go get -u github.com/gordonklaus/ineffassign
	- go get -u honnef.co/go/tools/cmd/staticcheck

install:
  - make deps

script:
  - hack/verify-codegen.sh
  - travis_wait 20 goveralls -service=travis-ci -package ./pkg/... -v
  - make e2e
