apiVersion: v1
entries:
  postgres-operator-ui:
  - apiVersion: v1
    appVersion: 1.5.0
    created: "2020-05-08T11:19:59.077858496+02:00"
    description: Postgres Operator UI provides a graphical interface for a convenient
      database-as-a-service user experience
    digest: 740298774491cb91f2b5f8814531aa8c6b1baddf8ad194ab29b191c86d440c73
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - ui
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator-ui
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-ui-1.5.0.tgz
    version: 1.5.0
generated: "2020-05-08T11:19:59.077159745+02:00"
