apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  pod_service_account_name: {{ template "postgres-operator.fullname" . }}
  docker_image: {{ .Values.docker_image }}
  debug_logging: "{{ .Values.configDebug.debug_logging }}"
  enable_database_access: "{{ .Values.configDebug.enable_database_access }}"
  repair_period: {{ .Values.repair_period }}
  resync_period: {{ .Values.resync_period }}
  spilo_privileged: "{{ .Values.spilo_privileged }}"
{{ toYaml .Values.configMap | indent 2 }}
{{ toYaml .Values.configUsers | indent 2 }}
{{ toYaml .Values.configKubernetes | indent 2 }}
{{ toYaml .Values.configNamespace | indent 2 }}
{{ toYaml .Values.configTimeouts | indent 2 }}
{{ toYaml .Values.configLoadBalancer | indent 2 }}
{{ toYaml .Values.configAwsOrGcp | indent 2 }}
{{ toYaml .Values.configTeamsApi | indent 2 }}
{{ toYaml .Values.configLoggingRestApi | indent 2 }}
