apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: {{ template "postgres-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
configuration:
  pod_service_account_name: operator
{{ toYaml .Values.config | indent 2 }}
{{ toYaml .Values.configCRD | indent 2 }}
  users:
{{ toYaml .Values.configUsers | indent 4 }}
  kubernetes:
{{ toYaml .Values.configKubernetes | indent 4 }}
  postgres_pod_resources:
{{ toYaml .Values.configPostgresPodResources | indent 4 }}
  timeouts:
{{ toYaml .Values.configTimeouts | indent 4 }}
  load_balancer:
{{ toYaml .Values.configLoadBalancer | indent 4 }}
  aws_or_gcp:
{{ toYaml .Values.configAwsOrGcp | indent 4 }}
  debug:
{{ toYaml .Values.configDebug | indent 4 }}
  teams_api:
{{ toYaml .Values.configTeamsApiCRD | indent 4 }}
  logging_rest_api:
{{ toYaml .Values.configLoggingRestApi | indent 4 }}
  scalyr:
{{ toYaml .Values.configScalyr | indent 4 }}
